name: Terraform CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        terraform init -backend-config="resource_group_name=azure-devops-rg" -backend-config="storage_account_name=tfstateazuredevops123" -backend-config="container_name=tfstate" -backend-config="key=terraform.tfstate"

    - name: Terraform Format
      working-directory: ./terraform
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        terraform plan -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" -out=tfplan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./terraform
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: |
        terraform apply -auto-approve -var "azure_client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "azure_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "azure_tenant_id=${{ secrets.AZURE_TENANT_ID }}" tfplan
